name: test-macos

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node: [23, 22, 20, 18]
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm install
          npm list
      - name: Run tests
        run: npm run test
      #- name: Run type checking
      #  run: npm run types
      - name: Run benchmark
        run: |
          npm run bench
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
