name: test-windows

on:  [workflow_dispatch]

jobs:
  test:
    runs-on: windows-2025
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Setup node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run:  npm install
      - name: Run tests
        run: npm run test:windows
